#!/bin/bash
set -e

# Execute from project root
cd "$(dirname "$0")/.."

# Build the library first (docs depend on it)
.bin/build

# Build the docs site
cd docs
npm ci  # Mainly for Netlify
npx nuxt generate
